Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EmployeeManagement.Models
{
    public class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public int DepartmentId { get; set; }
    }
}

Controllers/EmployeesController.cs
using EmployeeManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class EmployeesController : Controller
    {
        [HttpGet]
        public ActionResult List()
        {
            IEnumerable<EmployeeListViewModel> model = from employee in EmployeeRepository.GetAll()
                                                join department in DepartmentRepository.GetAll()
                                                on employee.DepartmentId equals department.DepartmentId
                                                select new EmployeeListViewModel()
                                                {
                                                    Name = employee.FirstName + " " + employee.LastName,
                                                    Department = department.DepartmentName,
                                                    Phone = employee.Phone,
                                                    EmployeeID = employee.EmployeeId
                                                };
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            AddEmployeeViewModel model = new AddEmployeeViewModel();

            model.Departments = GetDepartmentsSelectList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(AddEmployeeViewModel model)
        {
            if(ModelState.IsValid)
            {
                Employee employee = new Employee();
                employee.FirstName = model.FirstName;
                employee.LastName = model.LastName;
                employee.Phone = model.Phone;
                employee.DepartmentId = model.DepartmentId;

                EmployeeRepository.Add(employee);

                return RedirectToAction("List");
            }
            else
            {
                model.Departments = GetDepartmentsSelectList();

                return View(model);
            }

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var employee = EmployeeRepository.Get(id);

            var model = new EditEmployeeViewModel();
            model.FirstName = employee.FirstName;
            model.LastName = employee.LastName;
            model.DepartmentId = employee.DepartmentId;
            model.Phone = employee.Phone;
            model.EmployeeId = employee.EmployeeId;

            model.Departments = GetDepartmentsSelectList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                Employee employee = new Employee();
                employee.EmployeeId = model.EmployeeId;
                employee.FirstName = model.FirstName;
                employee.LastName = model.LastName;
                employee.Phone = model.Phone;
                employee.DepartmentId = model.DepartmentId;

                EmployeeRepository.Edit(employee);

                return RedirectToAction("List");
            }
            else
            {
                model.Departments = GetDepartmentsSelectList();

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            EmployeeRepository.Delete(id);
            return RedirectToAction("List");
        }

        private List<SelectListItem> GetDepartmentsSelectList()
        {
            return (from department in DepartmentRepository.GetAll()
                    select new SelectListItem()
                    {
                        Text = department.DepartmentName,
                        Value = department.DepartmentId.ToString()
                    }).ToList();
        }
    }
}

Views/Employees/Add.cshtml
@model EmployeeManagement.Models.AddEmployeeViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <h1>Add Employee</h1>
                @Html.ValidationSummary()
                @using (Html.BeginForm("Add", "Employees", FormMethod.Post))
            {
                    <div class="form-group">
                        <label>First Name</label>
                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Department</label>
                        @Html.DropDownListFor(m => m.DepartmentId, Model.Departments, new { @class = "form-control" })
                    </div>
                    @Html.ActionLink("Cancel", "List", "Employees", null, new { @class = "btn btn-default" })
                    <button class="btn btn-primary">Save</button>
                }
            </div>

        </div> 
    </div>
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/Employees/Edit.cshtml
@model EmployeeManagement.Models.EditEmployeeViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <h1>Edit Employee</h1>
                @Html.ValidationSummary()
                @using (Html.BeginForm("Edit", "Employees", FormMethod.Post))
                {
                    @Html.HiddenFor(m => m.EmployeeId)
                    <div class="form-group">
                        <label>First Name</label>
                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                    </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Department</label>
                            @Html.DropDownListFor(m => m.DepartmentId, Model.Departments, new { @class = "form-control" })
                        </div>
                        @Html.ActionLink("Cancel", "List", "Employees", null, new { @class = "btn btn-default" })
                        <button class="btn btn-primary">Save</button>
                }
            </div>

        </div>
    </div>
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/Employees/List.cshtml
@model IEnumerable<EmployeeManagement.Models.EmployeeListViewModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container"> 
        <div class="row">
            <div class="col-xs-12">
                <h1>Employees</h1>
                <p>@Html.ActionLink("Add a new employee", "Add", "Employees")</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Department</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var employee in Model)
                        {
                            <tr>
                                <td>@employee.Name</td>
                                <td>@employee.Phone</td>
                                <td>@employee.Department</td>
                            <td>
                                @Html.ActionLink("edit", "Edit", "Employees", new { id=employee.EmployeeID}, null)
                            </td>
                            <td>
                                @using (Html.BeginForm("Delete", "Employees", new { id = employee.EmployeeID }, FormMethod.Post))
                                {
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure you want to delete @employee.Name?');">Delete</button>
                                }
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>